spring:
  application:
    name: my-colony-back
  profiles:
    default: local
  threads:
    virtual:
      enabled: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
